stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - dalfcs_gitlab_docker_ci

deploy_test:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_TEST --api-key=$HEROKU_API_KEY
  environment:
    name: test
    url: https://food-cpg-management-test.herokuapp.com
  only:
    - development
  tags:
    - dalfcs_gitlab_docker_ci

deploy_production:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://food-cpg-management-production.herokuapp.com
  only:
    - master
  tags:
    - dalfcs_gitlab_docker_ci
